require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RankCartsController do

  # This should return the minimal set of attributes required to create a valid
  # RankCart. As you add validations to RankCart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RankCartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rank_carts as @rank_carts" do
      rank_cart = RankCart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rank_carts).should eq([rank_cart])
    end
  end

  describe "GET show" do
    it "assigns the requested rank_cart as @rank_cart" do
      rank_cart = RankCart.create! valid_attributes
      get :show, {:id => rank_cart.to_param}, valid_session
      assigns(:rank_cart).should eq(rank_cart)
    end
  end

  describe "GET new" do
    it "assigns a new rank_cart as @rank_cart" do
      get :new, {}, valid_session
      assigns(:rank_cart).should be_a_new(RankCart)
    end
  end

  describe "GET edit" do
    it "assigns the requested rank_cart as @rank_cart" do
      rank_cart = RankCart.create! valid_attributes
      get :edit, {:id => rank_cart.to_param}, valid_session
      assigns(:rank_cart).should eq(rank_cart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RankCart" do
        expect {
          post :create, {:rank_cart => valid_attributes}, valid_session
        }.to change(RankCart, :count).by(1)
      end

      it "assigns a newly created rank_cart as @rank_cart" do
        post :create, {:rank_cart => valid_attributes}, valid_session
        assigns(:rank_cart).should be_a(RankCart)
        assigns(:rank_cart).should be_persisted
      end

      it "redirects to the created rank_cart" do
        post :create, {:rank_cart => valid_attributes}, valid_session
        response.should redirect_to(RankCart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rank_cart as @rank_cart" do
        # Trigger the behavior that occurs when invalid params are submitted
        RankCart.any_instance.stub(:save).and_return(false)
        post :create, {:rank_cart => {  }}, valid_session
        assigns(:rank_cart).should be_a_new(RankCart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RankCart.any_instance.stub(:save).and_return(false)
        post :create, {:rank_cart => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rank_cart" do
        rank_cart = RankCart.create! valid_attributes
        # Assuming there are no other rank_carts in the database, this
        # specifies that the RankCart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RankCart.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => rank_cart.to_param, :rank_cart => { "these" => "params" }}, valid_session
      end

      it "assigns the requested rank_cart as @rank_cart" do
        rank_cart = RankCart.create! valid_attributes
        put :update, {:id => rank_cart.to_param, :rank_cart => valid_attributes}, valid_session
        assigns(:rank_cart).should eq(rank_cart)
      end

      it "redirects to the rank_cart" do
        rank_cart = RankCart.create! valid_attributes
        put :update, {:id => rank_cart.to_param, :rank_cart => valid_attributes}, valid_session
        response.should redirect_to(rank_cart)
      end
    end

    describe "with invalid params" do
      it "assigns the rank_cart as @rank_cart" do
        rank_cart = RankCart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RankCart.any_instance.stub(:save).and_return(false)
        put :update, {:id => rank_cart.to_param, :rank_cart => {  }}, valid_session
        assigns(:rank_cart).should eq(rank_cart)
      end

      it "re-renders the 'edit' template" do
        rank_cart = RankCart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RankCart.any_instance.stub(:save).and_return(false)
        put :update, {:id => rank_cart.to_param, :rank_cart => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rank_cart" do
      rank_cart = RankCart.create! valid_attributes
      expect {
        delete :destroy, {:id => rank_cart.to_param}, valid_session
      }.to change(RankCart, :count).by(-1)
    end

    it "redirects to the rank_carts list" do
      rank_cart = RankCart.create! valid_attributes
      delete :destroy, {:id => rank_cart.to_param}, valid_session
      response.should redirect_to(rank_carts_url)
    end
  end

end
