require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RankCriteriaController do

  # This should return the minimal set of attributes required to create a valid
  # RankCriterium. As you add validations to RankCriterium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "criteria" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RankCriteriaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rank_criteria as @rank_criteria" do
      rank_criterium = RankCriterium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rank_criteria).should eq([rank_criterium])
    end
  end

  describe "GET show" do
    it "assigns the requested rank_criterium as @rank_criterium" do
      rank_criterium = RankCriterium.create! valid_attributes
      get :show, {:id => rank_criterium.to_param}, valid_session
      assigns(:rank_criterium).should eq(rank_criterium)
    end
  end

  describe "GET new" do
    it "assigns a new rank_criterium as @rank_criterium" do
      get :new, {}, valid_session
      assigns(:rank_criterium).should be_a_new(RankCriterium)
    end
  end

  describe "GET edit" do
    it "assigns the requested rank_criterium as @rank_criterium" do
      rank_criterium = RankCriterium.create! valid_attributes
      get :edit, {:id => rank_criterium.to_param}, valid_session
      assigns(:rank_criterium).should eq(rank_criterium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RankCriterium" do
        expect {
          post :create, {:rank_criterium => valid_attributes}, valid_session
        }.to change(RankCriterium, :count).by(1)
      end

      it "assigns a newly created rank_criterium as @rank_criterium" do
        post :create, {:rank_criterium => valid_attributes}, valid_session
        assigns(:rank_criterium).should be_a(RankCriterium)
        assigns(:rank_criterium).should be_persisted
      end

      it "redirects to the created rank_criterium" do
        post :create, {:rank_criterium => valid_attributes}, valid_session
        response.should redirect_to(RankCriterium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rank_criterium as @rank_criterium" do
        # Trigger the behavior that occurs when invalid params are submitted
        RankCriterium.any_instance.stub(:save).and_return(false)
        post :create, {:rank_criterium => { "criteria" => "invalid value" }}, valid_session
        assigns(:rank_criterium).should be_a_new(RankCriterium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RankCriterium.any_instance.stub(:save).and_return(false)
        post :create, {:rank_criterium => { "criteria" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rank_criterium" do
        rank_criterium = RankCriterium.create! valid_attributes
        # Assuming there are no other rank_criteria in the database, this
        # specifies that the RankCriterium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RankCriterium.any_instance.should_receive(:update).with({ "criteria" => "MyString" })
        put :update, {:id => rank_criterium.to_param, :rank_criterium => { "criteria" => "MyString" }}, valid_session
      end

      it "assigns the requested rank_criterium as @rank_criterium" do
        rank_criterium = RankCriterium.create! valid_attributes
        put :update, {:id => rank_criterium.to_param, :rank_criterium => valid_attributes}, valid_session
        assigns(:rank_criterium).should eq(rank_criterium)
      end

      it "redirects to the rank_criterium" do
        rank_criterium = RankCriterium.create! valid_attributes
        put :update, {:id => rank_criterium.to_param, :rank_criterium => valid_attributes}, valid_session
        response.should redirect_to(rank_criterium)
      end
    end

    describe "with invalid params" do
      it "assigns the rank_criterium as @rank_criterium" do
        rank_criterium = RankCriterium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RankCriterium.any_instance.stub(:save).and_return(false)
        put :update, {:id => rank_criterium.to_param, :rank_criterium => { "criteria" => "invalid value" }}, valid_session
        assigns(:rank_criterium).should eq(rank_criterium)
      end

      it "re-renders the 'edit' template" do
        rank_criterium = RankCriterium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RankCriterium.any_instance.stub(:save).and_return(false)
        put :update, {:id => rank_criterium.to_param, :rank_criterium => { "criteria" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rank_criterium" do
      rank_criterium = RankCriterium.create! valid_attributes
      expect {
        delete :destroy, {:id => rank_criterium.to_param}, valid_session
      }.to change(RankCriterium, :count).by(-1)
    end

    it "redirects to the rank_criteria list" do
      rank_criterium = RankCriterium.create! valid_attributes
      delete :destroy, {:id => rank_criterium.to_param}, valid_session
      response.should redirect_to(rank_criteria_url)
    end
  end

end
